openapi: 3.0.1
info:
  title: TFT Service API
  description: ''
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://example.swagger.io/v2
tags:
- name: summoner
  description: Operations about summoner
paths:
  /summoner/{username}:
    get:
      tags:
      - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summoner'
        400:
          description: Invalid request
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        404:
          description: User not found
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
        500:
          description: Internal Server Error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    Summoner:
      type: object
      properties:
        summonerName:
          description: Summoner Name
          type: string
        summonerId:
          description: Encrypted summoner ID. Max length 63 characters.
          type: string
        puuid:
          description: Encrypted PUUID. Exact length of 78 characters.
          type: string
        summonerLevel:
          description: Summoner level associated with the summoner
          type: integer
          format: int64
        revisionDate:
          description: Date summoner was last modified specified as epoch milliseconds
          type: integer
          format: int64
    ServerError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
