server:
  port: 8080

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

com:
  fp:
    tft:
      downstream:
        apiKey: RGAPI-092f686c-0b61-4db4-ad90-e5c61792daa8
        summoner:
          base-uri: https://na1.api.riotgames.com/tft/summoner/v1/summoners/
          read-timeout: 5000
          connect-timeout: 5000

logging:
  level:
    root: INFO
    com.fp.tft: INFO
    org.apache.http.wire: INFO